# Generated by Django 4.2.8 on 2024-04-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_personsignup_remove_person_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='personsignup',
            name='city',
        ),
        migrations.RemoveField(
            model_name='personsignup',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personsignup',
            name='phonemnumber',
        ),
        migrations.AddField(
            model_name='personsignup',
            name='password',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
