# Generated by Django 4.2.8 on 2024-04-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_person_remove_personsignup_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personsignup',
            old_name='email',
            new_name='entered_email',
        ),
    ]
