# Generated by Django 4.2.8 on 2024-04-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_entered_email_personsignup_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personsignup',
            old_name='firstname',
            new_name='username',
        ),
    ]
