# Generated by Django 4.2.8 on 2024-04-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_firstname_personsignup_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personsignup',
            old_name='username',
            new_name='entered_username',
        ),
    ]
